name: goreleaser

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3 
      -
        name: git
        run: |
          git clone https://github.com/admpub/nging
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./nging
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      -
        name: rename
        run: |
          rename ​nging_?linux_amd64.tar.gz nging_linux_amd64.tar.gz ./nging/dist/nging_?linux_amd64.tar.gz

          rename nging_?darwin_amd64.tar.gz nging_darwin_amd64.tar.gz ./nging/dist/nging_?darwin_amd64.tar.gz

          rename nging_?linux_arm64.tar.gz nging_linux_arm64.tar.gz ./nging/dist/nging_linux_arm64.tar.gz

          rename nging_?linux_386.tar.gz nging_linux_386.tar.gz ./nging/dist/nging_?linux_386.tar.gz

          rename nging_?darwin_arm64.tar.gz nging_darwin_arm64.tar.gz ./nging/dist/nging_?darwin_arm64.tar.gz
      - 
        name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./nging/dist/*.tar.gz"
          tag: latest
          removeArtifacts: true
          token: ${{ secrets.TOKEN }}
