name: dev

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          submodules: true
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3 
      -
        name: Update Submodules
        run: git submodule foreach 'git fetch origin; git checkout $(git rev-parse --abbrev-ref HEAD); git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); git submodule update --recursive; git clean -dfx'
      -
        name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update submodules
          skip_dirty_check: false
          commit_user_name: Action Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Action <actions@github.com>
 
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./nging
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GORELEASER_CURRENT_TAG: "sqlite"
      -
        name: rename
        run: |
          sudo apt update
          sudo apt install rename -y
          rename -v "s/nging*linux_amd64\.tar\.gz/nging_linux_amd64\.tar\.gz/" ./nging/dist/nging*linux_amd64.tar.gz
          
          rename "s/nging*darwin_amd64\.tar\.gz/nging_darwin_amd64\.tar\.gz/" ./nging/dist/nging*darwin_amd64.tar.gz

          rename "s/nging*linux_arm64\.tar\.gz/nging_linux_arm64\.tar\.gz/" ./nging/dist/nging*linux_arm64.tar.gz

          rename "s/nging*linux_386\.tar\.gz/nging_linux_386\.tar\.gz/" ./nging/dist/nging*linux_386.tar.gz

          rename "s/nging*darwin_arm64\.tar\.gz/nging_darwin_arm64\.tar\.gz/" ./nging/dist/nging*darwin_arm64.tar.gz
      - 
        name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./nging/dist/*.tar.gz"
          tag: latest
          removeArtifacts: true
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
