name: stable

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3 
      -
        name: git
        run: |
          sudo apt update
          sudo apt install unzip wget -y
          wget https://github.com/admpub/nging/archive/refs/tags/v3.6.4.zip -O nging.zip
          unzip nging.zip
          mv nging-3.6.4 nging
          
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./nging
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      -
        name: rename
        run: |
          sudo apt update
          sudo apt install rename -y
          rename -v "s/nging*linux_amd64\.tar\.gz/nging_linux_amd64\.tar\.gz/" ./nging/dist/nging*linux_amd64.tar.gz
          
          rename "s/nging*darwin_amd64\.tar\.gz/nging_darwin_amd64\.tar\.gz/" ./nging/dist/nging*darwin_amd64.tar.gz

          rename "s/nging*linux_arm64\.tar\.gz/nging_linux_arm64\.tar\.gz/" ./nging/dist/nging*linux_arm64.tar.gz

          rename "s/nging*linux_386\.tar\.gz/nging_linux_386\.tar\.gz/" ./nging/dist/nging*linux_386.tar.gz

          rename "s/nging*darwin_arm64\.tar\.gz/nging_darwin_arm64\.tar\.gz/" ./nging/dist/nging*darwin_arm64.tar.gz
      - 
        name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./nging/dist/*.tar.gz"
          tag: nging-stable
          removeArtifacts: true
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
